version: "3.10"

services:
  backend:
    build: .
    restart: on-failure
    command: pipenv run python3 server.py
    volumes:
      - .:/code
    environment:
      - TWILIO_SID=<sid> #ignore if token in .env
      - TWILIO_AUTHTOKEN=<token> #ignore if token in .env
    ports:
      - "5000:5000"
